config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :scrapers, only: [:index, :new, :show]
end

app/models/scraper.rb
class Scraper < ActiveRecord::Base
  validates :hosts_files, presence: true

  require "mechanize"
  require "nokogiri"
  require "open-uri"


  def scrape
    count = 33

    agent = Mechanize.new
    proxy = agent.get("http://www.proxy4free.com/list/webproxy1.html")
    link = proxy.links[count]
    until link.uri.to_s != "" and link.text != ""
      count -= 1
      link = proxy.links[count]
    end
    proxy = link.click
    proxy_form = proxy.forms.last
    print "."

    until proxy.form.field.name == "q"
      count += 3
      proxy = agent.get("http://www.proxy4free.com/list/webproxy1.html")
      link = proxy.links[count]
      proxy = link.click
      proxy_form = proxy.forms.last
      print "."
    end

    files = {ad_servers: "ad_servers", malware: "emd", exploit: "exp",
            fraud: "fsa", spam: "grm", hpspam: "hfs", hijacked: "hjk",
            misleading: "mmt", illegal_pharma:"pha", phishing: "psh",
            piracy: "wrz"}


    files.each do |key, value|
      @hosts_file = []
      proxy_form.q = "http://hosts-file.net/#{value}.txt"
      proxy = agent.submit(proxy_form)
      print "."
      doc = Nokogiri::HTML(open(proxy.uri.to_s))
      doc_text_full = doc.css("p").to_s
      doc_text_parse = doc_text_full.gsub(/^<p>.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n/, '')
      doc_text_end_parse = doc_text_parse.gsub(/# Hosts:.*\n<\/p>/,'')
      doc_text_ad_parse = doc_text_end_parse.gsub(/#\r\n/,'')
      doc_text = doc_text_ad_parse.gsub(/127.0.0.1\t/,'')
      text = doc_text.split("\r\n")

      text.each do |t|
        @hosts_file << t
      end

      fname = "text_files/#{key.to_s}.txt"
      File.open(fname, "w+") do |f|
        f.puts(@hosts_file)
      end
      print ""
    end

    @hosts_file = []
    proxy = "http://www.malwaredomainlist.com/hostslist/hosts.txt"

    doc = Nokogiri::HTML(open(proxy))
    doc_text_full = doc.css("p").text
    doc_text_parse = doc_text_full.gsub(/.*#/, '')
    doc_text_end_parse = doc_text_parse.gsub(/.*localhost/,'')
    doc_text = doc_text_end_parse.gsub(/127.0.0.1/,'')
    text_empty = doc_text.split("\r\n")
    text = text_empty.reject(&:empty?)

    text.each do |t|
      @hosts_file << t.strip
    end

    fname = "text_files/malwaredomainlist.txt"
    File.open(fname, "w+") do |f|
      f.puts(@hosts_file)
    end

    print "."
    print "done"


    @hosts_file = []
    proxy = "http://www.malwaredomainlist.com/hostslist/ip.txt"
    doc = Nokogiri::HTML(open(proxy))
    text = doc.css("p").text.split("\r\n")

    text.each do |t|
      @hosts_file << t.strip
    end

    fname = "text_files/malwaredomainlist_ip.txt"
    File.open(fname, "w+") do |f|
      f.puts(@hosts_file)
    end

    Scraper.create(name: "updated", hosts_files: "hosts files now in text files")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :options_for_interval

  def options_for_interval
    [
      ["Every other day", ":hour"],
      ["Every six hours", "6.hours"],
      ["Every twelve hours", "12.hours"],
      ["Every day", ":day"],
      ["Every other day", "2.days"],
      ["Every three days", "3.days"],
      ["Every four day", "4.days"],
      ["Every five day", "5.days"],
      ["Every week", ":week"],
      ["Every weekend", ":weekend"],
      ["Every weekday", ":weekday"]
    ]
  end

  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    if Scraper.count == 0
      @scraped = "no hosts-files scraped"
    else
      @scraped = Scraper.last.created_at.localtime.to_formatted_s(:long)
    end
  end
end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController
  def index
    @scraper = ["ad_servers", "malware", "exploit", "fraud", "spam", "hpspam",
                "hijacked", "misleading", "illegal_pharma", "phishing", "piracy"]
    @malware = ["malwaredomainlist", "malwaredomainlist_ip"]
  end

  def show
    render file: "text_files/#{params["id"]}.txt",  content_type: 'text/plain'
  end

  def new
    Scraper.new.scrape
    redirect_to scrapers_path
  end
end

app/views/homes/index.html.erb
<div class="title">
  <div class="panel">
    <h1>The Proxy Bot</h1>
    <h2>Schedule a bot to keep your hosts files up to date</h2>
  </div>
</div>
<ul class="row">
  <li>
    <div class="panel">
      <h3><%= link_to "View Threat Feeds", scrapers_path %></h3>
    </div>
  </li>
  <li>
    <div class="panel">
      <h2>Feeds were last updated at</h2>
      <h3><%= @scraped %></h3>
    </div>
  </li>
  <li>
    <div class="panel">
      <%= link_to "Force Update", new_scraper_path %>
    </div>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proxy Bot</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>
  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Proxy Bot</a></h1>
        </li>
      </ul>
    </nav>

    <%= yield %>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>
    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
  </body>
</html>

app/views/scrapers/index.html.erb
<div class="title">
  <div class="panel">
    <h1>The Proxy Bot</h1>
  </div>
</div>
<div class="panel">
  <h2>Host_files.net</h2>
</div>
<ul class="small-block-grid-3">
  <% @scraper.each do |type| %>
    <li>
      <div class="panel">
        <%= link_to type, scraper_path(type) + ".txt" %>
      </div>
    </li>
  <% end %>
</ul>
<div class="panel">
  <h2>Malware Domain List</h2>
</div>
<ul class="small-block-grid-2">
  <% @malware.each do |type| %>
    <li>
      <div class="panel">
        <%= link_to type, scraper_path(type) + ".txt" %>
      </div>
    </li>
  <% end %>
</ul>